-- -- auto-generated definition
-- create table "Order"
-- (
--     id        uuid not null
--         constraint orders_pk
--             primary key,
--     time      integer,
--     beverages varchar,
--     size      varchar,
--     sugar     integer
-- );
--
-- alter table "Order"
--     owner to postgres;
